---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1
Setup i chincs fortæller at denne køres hver gang

```{r setup}
library(tidyverse)
library(here)
source(here("R/functions.R"))
```


## Importing new data

```{r}
#| eval: false 
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


## Create my first function and documentation of it

```{r}
#| eval: false 
#' Add two numbers together.
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```


```{r}
#| eval: false
#| output: false #bliver ikke printet i html
#|
#' Read in one nurses' stress data file.
#'
#' @param file_path A path to a datafile
#'
#' @returns outputs a dataframe/ tibble

read <- function(file_path) {
  data <- file_path |>
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(data)
}
```


```{r}
#| eval: false 

# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)


```
